remove legacy u2f field values on delete credential
silinternational/serverless-mfa-api-go pull request #22
Opened 2022-07-18 13:42 UTC by Baggerone

2022-07-18 14:04 UTC, jason-jackson approved these changes

2022-07-20 14:58 UTC, forevermatt requested changes

2022-07-20 14:58 UTC, forevermatt commented on fixtures_test.go
> +	testUser0.EncryptedPublicKey = apiKey0.Key
It may be better to use truly dummy / made-up data, to avoid giving the impression that certain fields correspond to other fields here (e.g. that apiKey0.Key is related somehow to both the KeyHandle and the PublicKey... which I think are two completely separate pieces of data). Just a thought.

2022-07-20 14:58 UTC, forevermatt commented on user.go
> +	u.AppId = ""
I don't know if this matters, but we only store the "Encrypted..." forms of each of these in the DynamoDB, not the unencrypted ones.

2022-07-20 14:58 UTC, forevermatt commented on user.go
> +	if credIDHash == u.EncryptedAppId {
Can you help me understand why the EncryptedAppID is what you used to indicate that the old U2F fields should be deleted? I think I was expecting some string like `"u2f"` to be used for that. (i.e. We use "u2f" to indicate to delete the U2F fields, otherwise we use an actual WebAuthn CredentialID to indicate which WebAuthn credential to delete).

2022-07-20 17:18 UTC, Baggerone commented on user.go
> +	if credIDHash == u.EncryptedAppId {
I based it on the code that was already there, e.g. line 315 and line 355) (below).  Also, it was listed as one of the legacy U2F fields on the DynamoUser struct.

```
	// If user has registered U2F creds, check if RPIDHash is actually hash of AppId
	// if so, replace authenticator data RPIDHash with a hash of the RPID for validation
	if u.EncryptedAppId != "" {
		appid, err := u.ApiKey.DecryptLegacy([]byte(u.EncryptedAppId))
```

2022-07-20 20:27 UTC, forevermatt commented on user.go
> +	if credIDHash == u.EncryptedAppId {
While EncryptedAppId is one of the legacy U2F fields on the DynamoUser struct, I don't think it will work as a value that ID Broker can send to indicate "Delete the U2F stuff, rather than a WebAuthn credential", because I don't think ID Broker will know what the EncryptedAppId value is. The AppId is encrypted by the serverless code, and Broker never sees that value.

I think Broker will just have WebAuthn Credential ID hashes (in a new table) or, if the user is trying to delete a Security Key that Broker doesn't have a WebAuthn Credential ID hash for, Broker will need to assume it's a legacy U2F key and just pass something to serverless-mfa-api-go indicating that it's a U2F key. That's why I keep thinking that we'll want to use something like "u2f" as the (fake) Credential ID hash used to indicate that it's actually the U2F fields that should be deleted.

2022-07-21 12:14 UTC, Baggerone commented on user.go
> +	if credIDHash == u.EncryptedAppId {
Ok, I get your point. How about "legacy-u2f" as the credential ID?

2022-07-21 15:15 UTC, forevermatt commented on user.go
> +	LegacyU2FCredID = "legacy-u2f"
Yes, excellent solution 👍

2022-07-21 15:18 UTC, forevermatt commented on lambda/main.go
> +	// Alternatively, if the id param matches the user's EncryptedAppID
```suggestion
	// Alternatively, if the id param indicates that a U2F key should be removed
```

2022-07-21 15:19 UTC, forevermatt commented on server/main.go
> +		// Alternatively, if the id param matches the user's EncryptedAppID
```suggestion
		// Alternatively, if the id param indicates that a U2F key should be removed
```

2022-07-21 15:19 UTC, forevermatt commented on user.go
> +//  Alternatively, if the given credential id matches the user's EncryptedAppID
```suggestion
//  Alternatively, if the given credential id indicates that a U2F key should be removed
```

2022-07-21 18:03 UTC, merged